### ISSUE TITLE
小米8 运行后，反复进入桌面，导致手机无法使用

### ISSUE THREAD

**Issue by lvpeng1229** [wangjianxiandev/Weather#1]
小米8 ，Android10，MIUI版本12.0.1稳定版
运行后，反复进入桌面，导致手机无法使用。怀疑是定位功能导致的。只能使用adb 命令  adb uninstall com.wjx.android.weather
卸载掉后，才能正常使用手机。这个问题太坑了！！！

**Comment by wangjianxiandev** [comment]
> 小米8 ，Android10，MIUI版本12.0.1稳定版
> 运行后，反复进入桌面，导致手机无法使用。怀疑是定位功能导致的。只能使用adb 命令 adb uninstall com.wjx.android.weather
> 卸载掉后，才能正常使用手机。这个问题太坑了！！！

收到，晚上回家看下

**Comment by wangjianxiandev** [comment]
> 小米8 ，Android10，MIUI版本12.0.1稳定版
> 运行后，反复进入桌面，导致手机无法使用。怀疑是定位功能导致的。只能使用adb 命令 adb uninstall com.wjx.android.weather
> 卸载掉后，才能正常使用手机。这个问题太坑了！！！

没复现，具体日志麻烦发一下，一起学习~
