### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by wkbin** [wangjianxiandev/Weather#3]
两个按钮同时点击会引起闪退，比如个人博客和项目源码同时点击

**Comment by wangjianxiandev** [comment]
看到该现象了，晚上回去看下~

**Comment by wangjianxiandev** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： 王克斌 <notifications@github.com>日期： 2020年10月15日周四 14:21收件人： wangjianxiandev/Weather <Weather@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [wangjianxiandev/Weather] 闪退 (#3)

两个按钮同时点击会引起闪退，比如个人博客和项目源码同时点击

**Comment by wangjianxiandev** [comment]
> 两个按钮同时点击会引起闪退，比如个人博客和项目源码同时点击

已解决
